name: Testing
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  my-job:
    name: tests
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - name: Install Dependencies
        run: bun install
      - name: Run Tests
        run: bun run test
      - name: Run Integrated Tests
        run: bun run test:integration
